server:
  port: 9998

cookies:
  rail_expiration: "1567295388014"
  rail_deviceid: "eZBQ_NS9I7CKaLglysYnBLeg9ivC554YEsqyucYsJCW6QjrlK6E48lkgOLxYClB4kKys3n6vRJgID946hUQaIOLDzQZ6aPbY3FyjShsJxgBOkH-srT5nV_IHUxmGSx3lzoSvmWLXsUxZROIaF9E8hlhSVZNEJWpL"
config:
  # 是否启用代理
  enableProxy: false
  # 代理 HOST
  proxyHost: 127.0.0.1
  # 代理端口
  proxyPort: 12639
  host: "kyfw.12306.cn"
  base_url: "https://kyfw.12306.cn"
  queryTicketSellpTime: 1
  pythonPath: "python"
  logdevicePath: "classpath:logdevice.js"

api:
  station: "${config.base_url}/otn/resources/js/framework/station_name.js?station_version=1.9098"
  getJs: "${config.base_url}/otn/HttpZF/GetJS"
  logdevice: "${config.base_url}/otn/HttpZF/logdevice?algID=kNxKEJAs7D&hashCode=B6sCkh9vcRBYxziLrcshVAdpXJhYvJ_38tLFLhGSgmY&FMQw=0&q4f3=zh-CN&VPIf=1&custID=133&VEek=unspecified&dzuS=0&yD16=0&EOQP=c227b88b01f5c513710d4b9f16a5ce52&lEnu=2886729839&jp76=d41d8cd98f00b204e9800998ecf8427e&hAqN=MacIntel&platform=WEB&ks0Q=d41d8cd98f00b204e9800998ecf8427e&TeRS=529x960&tOHY=24xx540x960&Fvje=i1l1s1&q5aJ=-8&wNLf=99115dfb07133750ba677d055874de87&0aew=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010.14;%20rv:68.0)%20Gecko/20100101%20Firefox/68.0&E3gR=9ed513ad4028337a9c532447332b9bbc&timestamp=%s"
  init: "${config.base_url}/otn/leftTicket/init"
  leftTicket: "${config.base_url}/otn/leftTicket/query?leftTicketDTO.train_date=%s&leftTicketDTO.from_station=%s&leftTicketDTO.to_station=%s&purpose_codes=ADULT"
  loginConfig: "${config.base_url}/otn/login/conf"
  passengers: "${config.base_url}/otn/passengers/query"
  captchaImage: "${config.base_url}/passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&_=%s"
  uamtkStatic: "${config.base_url}/passport/web/auth/uamtk-static?appid=otn"
  login: "${config.base_url}/passport/web/login"
  captchaCheck: "${config.base_url}/passport/captcha/captcha-check?answer=%s&rand=sjrand&login_site=E&_=%s"
  uamtk: "${config.base_url}/passport/web/auth/uamtk"
  uamauthclient: "${config.base_url}/otn/uamauthclient"
  checkUser: "${config.base_url}/otn/login/checkUser"
  submitOrderRequest: "${config.base_url}/otn/leftTicket/submitOrderRequest"
  initDc: "${config.base_url}/otn/confirmPassenger/initDc"
  getPassengerDTOs: "${config.base_url}/otn/confirmPassenger/getPassengerDTOs"
  checkOrderInfo: "${config.base_url}/otn/confirmPassenger/checkOrderInfo"
  checkRandCodeAnsyn: "${config.base_url}/otn/passcodeNew/checkRandCodeAnsy"
  getQueueCount: "${config.base_url}/otn/confirmPassenger/getQueueCount"
  confirmSingleForQueue: "${config.base_url}/otn/confirmPassenger/confirmSingleForQueue"
  queryOrderWaitTime: "${config.base_url}/otn/confirmPassenger/queryOrderWaitTime?random=%s&tourFlag=dc&_json_att=&REPEAT_SUBMIT_TOKEN=%s"
  notice: "dysmsapi.aliyuncs.com"

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:sqlite:db/ticket.db"
    driver-class-name: org.sqlite.JDBC
  profiles:
    include:
      - user
      - sms

swagger:
  enabled: true
  title: 12306抢票系统
  description: 12306抢票系统
  webBasePackage: com.qianxunclub.ticket.controller
  author: 千寻啊千寻
  url: qianxunclub.com
  email: qianxunclub@qq.com

logging:
  level:
    com.qianxunclub: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr([%50t]){faint} %clr(:){faint} %m%n%wEx"
