server:
  port: 9998

config:
  # 是否启用代理
  enableProxy: false
  # 代理 HOST
  proxyHost: 127.0.0.1
  # 代理端口
  proxyPort: 12639
  host: "kyfw.12306.cn"
  base_url: "https://kyfw.12306.cn"
  # 随机查询时间，取值：min-max，范围随机
  queryTicketSleepTime:
    min: 1
    max: 3
  pythonPath: "python"

api:
  station: "/otn/resources/js/framework/station_name.js?station_version=1.9126"
  init: "/otn/leftTicket/init"
  leftTicket: "/otn/leftTicket/queryO?leftTicketDTO.train_date=%s&leftTicketDTO.from_station=%s&leftTicketDTO.to_station=%s&purpose_codes=ADULT"
  loginConfig: "/otn/login/conf"
  passengers: "/otn/passengers/query"
  captchaImage: "/passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&_=%s"
  uamtkStatic: "/passport/web/auth/uamtk-static"
  login: "/passport/web/login"
  captchaCheck: "/passport/captcha/captcha-check?answer=%s&rand=sjrand&login_site=E&_=%s"
  uamtk: "/passport/web/auth/uamtk"
  uamauthclient: "/otn/uamauthclient"
  checkUser: "/otn/login/checkUser"
  submitOrderRequest: "/otn/leftTicket/submitOrderRequest"
  initDc: "/otn/confirmPassenger/initDc"
  getPassengerDTOs: "/otn/confirmPassenger/getPassengerDTOs"
  checkOrderInfo: "/otn/confirmPassenger/checkOrderInfo"
  checkRandCodeAnsyn: "/otn/passcodeNew/checkRandCodeAnsy"
  getQueueCount: "/otn/confirmPassenger/getQueueCount"
  confirmSingleForQueue: "/otn/confirmPassenger/confirmSingleForQueue"
  queryOrderWaitTime: "/otn/confirmPassenger/queryOrderWaitTime?random=%s&tourFlag=dc&_json_att=&REPEAT_SUBMIT_TOKEN=%s"
  notice: "dysmsapi.aliyuncs.com"

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:sqlite:db/ticket.db"
    driver-class-name: org.sqlite.JDBC
  profiles:
    include:
      - cookie
      - user
      - sms

swagger:
  enabled: true
  title: 12306抢票系统
  description: 12306抢票系统
  webBasePackage: com.qianxunclub.ticket.controller
  author: 千寻啊千寻
  url: qianxunclub.com
  email: qianxunclub@qq.com

logging:
  level:
    com.qianxunclub: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr([%50t]){faint} %clr(:){faint} %m%n%wEx"
