## 可配置多乘客
#user.ticket-info:
#  - #  乘客编号
#    #  获取方法1：
#    #  调用 com.qianxunclub.ticket.GetPassengerTest 里面的 getPassenger 方法，可以打印出来对应的值
#    #
#    #  获取方法2：
#    #  登录12306官网成功后
#    #  访问：https://kyfw.12306.cn/otn/passengers/query?pageIndex=1&pageSize=100
#    #  找对对应乘客的【allEncStr】的值
#    allEncStr: 0cd61f3c223e6897bf62a82a5e769791c33fde697dfc7fd3b750aaa8a8d6329d
#    #  12306用户名
#    username: wang61039013
#    #  12306密码
#    password: Wy61039013
#    #  出发日期
#    date: 2020-01-15
#    #  出发站点
#    from: 南昌
#    #  到达站点
#    to: 哈尔滨
#    #  车次
#    trainNumber: Z112
#    #  乘车人姓名
#    realName: 王忠阳
#    #  乘车人手机号码
#    mobile: 18593037109
#    #  座位选择：从上往下，优先购买上面
#    #  YINGWO：硬卧
#    #  RUANWO：软卧
#    #  TWO：二等座
#    #  RUANZUO：软座
#    #  YINGZUO：硬座
#    #  ONE：一等座
#    #  SHANGWUZUO：商务座
#    #  GAOJIRUANWO：高级软卧
#    #  WUZUO：无座
#    seat:
#      - YINGZUO
#      - RUANWO
##  多账号抢票配置
##  - allEncStr: 1
##    username: XXXX
##    password: XXXX
##    date: 2019-08-14
##    from: 深圳
##    to: 三门峡南
##    trainNumber: XXXX
##    realName: XXXX
##    mobile: XXXX
##    seat:
##      - ONE
##      - WUZUO
