version: '2.2'
services:
  ticket:
    image: ${TICKET_IMAGE:-docker.pkg.github.com/qianxunclub/ticket/ticket:docker-base-layer}
    ports:
      - "9998:9998"
      - "5005:5005"
    volumes:
      - ../db/ticket.db:/db/ticket.db
      - ../temp:/temp
      - ../src/main/resources/application.yml:/application.yml
      - ../src/main/resources/application-cookie.yml:/application-cookie.yml
      - ../src/main/resources/application-sms.yml:/application-sms.yml
      - ../src/main/resources/application-user.yml:/application-user.yml
